name: Terraform Plan & apply the Development  environment

on:
  pull_request:
    branches:
      - development


jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup Terraform  
      uses: hashicorp/setup-terraform@v3
      with:
	terraform_version: 1.9.4

    - name: Initialize Terraform
      run: terraform init


     - name: Terraform plan when the pull request is raised in the repo
       run: terraform plan

     - name: Terraform applies when the pull request is merged in the repo
       run: terraform apply & auto-approve
       env:
	 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
	 ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
